name: Grafana Report to Slack

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:       # Allow manual trigger

jobs:
  send_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure github-actions-example folder exists
        run: mkdir -p github-actions-example

      - name: Render Grafana Dashboard Panel
        id: render
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GRAFANA_SERVICEACCOUNT_TOKEN }}" \
            -o panel.png \
            "https://${{ vars.GRAFANA_INSTANCE }}.grafana.net/render/d-solo/${{ vars.GRAFANA_DASHBOARD_ID }}?panelId=${{ vars.GRAFANA_PANEL_ID }}&width=1000&height=500&tz=UTC"
          echo "Rendered panel saved as panel.png: $(ls -lh panel.png)"
        working-directory: github-actions-example

      - name: Commit and push panel.png to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-actions-example/panel.png
          git commit -m "Update panel.png from workflow run" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/wcall/GrafanaReportToSlackGitHubAction.git
          git push origin HEAD
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Output panel.png permalink
        id: get_permalink_url
        run: |
          permalink="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}/refs/heads/main/github-actions-example/panel.png"
          echo "Permalink: $permalink"
          echo "permalink=$permalink" >> $GITHUB_OUTPUT
          echo "Permalink URL: $permalink"

      - name: Get Slack upload URL
        id: get_upload_url
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          FILESIZE=$(stat -c%s panel.png)
          echo "File size of panel.png: $FILESIZE bytes"
          response=$(curl -X POST "https://slack.com/api/files.getUploadURLExternal" \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-Type: application/json; charset=utf-8" \
            --data-raw '{
                "filename": "panel.png",
                "length": '"$FILESIZE"'
            }')
          echo "Response from Slack API: $response"
          upload_url=$(echo $response | jq -r '.upload_url')
          file_id=$(echo $response | jq -r '.file_id')
          echo "upload_url=$upload_url" >> $GITHUB_OUTPUT
          echo "file_id=$file_id" >> $GITHUB_OUTPUT
          echo "Upload URL: $upload_url"
          echo "File ID: $file_id"
        working-directory: github-actions-example

      - name: Upload Image to Slack
        run: |
          echo "Upload URL: ${{ steps.get_upload_url.outputs.upload_url }}"
          curl -s -X PUT -H "Content-Type: application/octet-stream" \
            --data-binary "@panel.png" \
            "${{ steps.get_upload_url.outputs.upload_url }}"
        working-directory: github-actions-example

      - name: Complete Slack file upload
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.SLACK_CHANNEL_ID }}
        run: |
          curl -s -X POST "https://slack.com/api/files.completeUploadExternal" \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"files":[{
              "id":"'"${{ steps.get_upload_url.outputs.file_id }}"'",
              "channels":["'"$SLACK_CHANNEL_ID"'"]}]}'
        working-directory: github-actions-example
