name: Grafana Report to Slack

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:       # Allow manual trigger

jobs:
  send_report:
    runs-on: ubuntu-latest

    steps:
      - name: Render Grafana Dashboard Panel
        id: render
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GRAFANA_SERVICEACCOUNT_TOKEN }}" \
            -o panel.png \
            "https://${{ vars.GRAFANA_INSTANCE }}.grafana.net/render/d-solo/${{ vars.GRAFANA_DASHBOARD_ID }}?panelId=1&width=1000&height=500&tz=UTC"

      - name: Create Slack Payload JSON
        run: |
          base64_image=$(base64 -w 0 panel.png)
          cat <<EOF > slack_payload.json
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Scheduled Grafana Report (every 6h)*"
                }
              },
              {
                "type": "image",
                "image_url": "data:image/png;base64,$base64_image",
                "alt_text": "Grafana Report"
              }
            ]
          }
          EOF

      - name: Upload Image to Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload-file-path: ./slack_payload.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
